
INSERT INTO USUARIOS (NOMBRE,USERNAME, CORREO,PASSWORD,ROLE,ACTIVO) VALUES('admin','admin','admin@gmail.com','$2a$10$Z6CnjF0bwevv2C3DqcMhq.1Fq3jgSSKdutfcoRHPhzurYRmhY.3hm','ADMIN','true');

INSERT INTO TELEFONOS (NUMERO,CODIGO_CIUDAD,CODIGO_PAIS,USUARIO_ID) VALUES(0,0,0,1);
